# Configurations
title:            Casper Java SDK
longtitle:        Java 8+ Casper RPC Client SDK
author:           Alexandre Carvalho
email:            adcarvalho@gmail.com
description: >
  Cookbooks, code reports and documentation.

baseurl:          '/casper-sdk'

remote_theme:     oak/architect
